import {
  Code, Search, Layout, Server, Cpu, Database,
  Zap, Shield, FlaskConical, Terminal, Users,
  Activity, Layers, Wrench
} from 'lucide-react';

export const AGENTS = [
  {
    id: 'senior-dev',
    name: 'Sarah Chen',
    title: 'Senior Developer',
    emoji: '👩‍💻',
    description: 'Full-stack development and architectural decisions',
    icon: Code,
    status: 'idle',
    progress: 0,
    tags: ['React', 'Review', 'Architecture'],
    colorClass: 'text-cyan-300',
    progressColor: '#67e8f9',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=120&fit=crop',
    projectCount: 42,
    aiProvider: 'Gemini',
    aiModel: '1.5 Pro',
    aiLogoUrl: 'https://www.gstatic.com/images/branding/product/2x/gemini_32dp.png',
    currentTaskId: 'DEV-402',
    currentTaskName: 'Refactoring core authentication module architecture'
  },
  {
    id: 'code-reviewer',
    name: 'Elena Rodriguez',
    title: 'Code Reviewer',
    emoji: '🔵',
    description: 'Code quality, security, and best practices',
    icon: Search,
    status: 'idle',
    progress: 0,
    tags: ['TypeScript', 'Security', 'Best Practices'],
    colorClass: 'text-violet-300',
    progressColor: '#c4b5fd',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=400&h=120&fit=crop',
    projectCount: 128,
    aiProvider: 'ChatGPT',
    aiModel: 'GPT-4o',
    aiLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    currentTaskId: 'REV-102',
    currentTaskName: 'Waiting for new pull requests to analyze'
  },
  {
    id: 'frontend-spec',
    name: 'Maya Patel',
    title: 'Frontend Specialist',
    emoji: '🎨',
    description: 'UI/UX and modern frontend frameworks',
    icon: Layout,
    status: 'idle',
    progress: 0,
    tags: ['React', 'Quality', 'Strategy'],
    colorClass: 'text-pink-300',
    progressColor: '#f9a8d4',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=400&h=120&fit=crop',
    projectCount: 35,
    aiProvider: 'Claude',
    aiModel: '3.5 Sonnet',
    aiLogoUrl: 'https://avatars.githubusercontent.com/u/76839336?s=200&v=4',
    currentTaskId: 'FE-55',
    currentTaskName: 'Designing the new dashboard layout and component system'
  },
  {
    id: 'backend-expert',
    name: 'David Kim',
    title: 'Backend Expert',
    emoji: '🦈',
    description: 'Server-side, databases, and APIs',
    icon: Server,
    status: 'idle',
    progress: 0,
    tags: ['Go', 'Review', 'Scalability'],
    colorClass: 'text-blue-300',
    progressColor: '#93c5fd',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400&h=120&fit=crop',
    projectCount: 56,
    aiProvider: 'Gemini',
    aiModel: '1.5 Flash',
    aiLogoUrl: 'https://www.gstatic.com/images/branding/product/2x/gemini_32dp.png',
    currentTaskId: 'BE-89',
    currentTaskName: 'Optimizing query performance for high-traffic endpoints'
  },
  {
    id: 'soft-arch',
    name: 'James Wilson',
    title: 'Software Architect',
    emoji: '🧬',
    description: 'System design and technology strategy',
    icon: Cpu,
    status: 'idle',
    progress: 0,
    tags: ['Architecture', 'Scalability', 'Strategy'],
    colorClass: 'text-yellow-300',
    progressColor: '#fde047',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=400&h=120&fit=crop',
    projectCount: 24,
    aiProvider: 'ChatGPT',
    aiModel: 'o1-preview',
    aiLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    currentTaskId: 'ARCH-14',
    currentTaskName: 'Evaluating microservices migration strategy'
  },
  {
    id: 'api-designer',
    name: 'Robert Taylor',
    title: 'API Designer',
    emoji: '🐴',
    description: 'RESTful and GraphQL API design',
    icon: Terminal,
    status: 'idle',
    progress: 0,
    tags: ['GraphQL', 'Documentation', 'Strategy'],
    colorClass: 'text-orange-300',
    progressColor: '#fdba74',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=400&h=120&fit=crop',
    projectCount: 82,
    aiProvider: 'Claude',
    aiModel: '3 Opus',
    aiLogoUrl: 'https://avatars.githubusercontent.com/u/76839336?s=200&v=4',
    currentTaskId: 'API-31',
    currentTaskName: 'Designing RESTful endpoints for user management'
  },
  {
    id: 'db-expert',
    name: 'Michael Brown',
    title: 'Database Expert',
    emoji: '🦀',
    description: 'Database optimization and data modeling',
    icon: Database,
    status: 'idle',
    progress: 0,
    tags: ['PostgreSQL', 'Sharding', 'Scalability'],
    colorClass: 'text-red-300',
    progressColor: '#fca5a5',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=400&h=120&fit=crop',
    projectCount: 41,
    aiProvider: 'Gemini',
    aiModel: '1.5 Pro',
    aiLogoUrl: 'https://www.gstatic.com/images/branding/product/2x/gemini_32dp.png',
    currentTaskId: 'DB-44',
    currentTaskName: 'Normalizing schema and creating migration scripts'
  },
  {
    id: 'devops-expert',
    name: 'Thomas Anderson',
    title: 'DevOps Expert',
    emoji: '🐟',
    description: 'CI/CD, infrastructure, and deployment',
    icon: Zap,
    status: 'idle',
    progress: 0,
    tags: ['AWS', 'Compliance', 'Roadmap'],
    colorClass: 'text-indigo-300',
    progressColor: '#a5b4fc',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1550684847-75bdda21cc95?w=400&h=120&fit=crop',
    projectCount: 63,
    aiProvider: 'ChatGPT',
    aiModel: 'GPT-4o',
    aiLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    currentTaskId: 'OPS-77',
    currentTaskName: 'Configuring CI/CD pipeline for staging environment'
  },
  {
    id: 'perf-guru',
    name: 'Chris Evans',
    title: 'Performance Guru',
    emoji: '🐬',
    description: 'Optimization and performance analysis',
    icon: Activity,
    status: 'idle',
    progress: 0,
    tags: ['Profiling', 'Review', 'Scalability'],
    colorClass: 'text-teal-300',
    progressColor: '#5eead4',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=400&h=120&fit=crop',
    projectCount: 19,
    aiProvider: 'Claude',
    aiModel: '3.5 Sonnet',
    aiLogoUrl: 'https://avatars.githubusercontent.com/u/76839336?s=200&v=4',
    currentTaskId: 'PERF-08',
    currentTaskName: 'Profiling memory leaks in real-time data processing'
  },
  {
    id: 'security-exp',
    name: 'Sophia Williams',
    title: 'Security Expert',
    emoji: '🛡️',
    description: 'Security assessment and threat analysis',
    icon: Shield,
    status: 'idle',
    progress: 0,
    tags: ['Encryption', 'Pentesting', 'Strategy'],
    colorClass: 'text-rose-300',
    progressColor: '#fda4af',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=400&h=120&fit=crop',
    projectCount: 37,
    aiProvider: 'Gemini',
    aiModel: '1.5 Flash',
    aiLogoUrl: 'https://www.gstatic.com/images/branding/product/2x/gemini_32dp.png',
    currentTaskId: 'SEC-21',
    currentTaskName: 'Running penetration tests on authentication flow'
  },
  {
    id: 'tech-lead',
    name: 'Daniel Lee',
    title: 'Tech Lead',
    emoji: '🐲',
    description: 'Technical leadership and team guidance',
    icon: Users,
    status: 'idle',
    progress: 0,
    tags: ['Node.js', 'Quality', 'Mentoring'],
    colorClass: 'text-purple-300',
    progressColor: '#d8b4fe',
    avatarUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=120&fit=crop',
    projectCount: 12,
    aiProvider: 'ChatGPT',
    aiModel: 'o1-preview',
    aiLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    currentTaskId: 'LEAD-03',
    currentTaskName: 'Reviewing sprint backlog and team assignments'
  },
  {
    id: 'fullstack-dev',
    name: 'Isabella Garcia',
    title: 'Full Stack Developer',
    emoji: '⭐',
    description: 'End-to-end development solutions',
    icon: Layers,
    status: 'idle',
    progress: 0,
    tags: ['Next.js', 'Review', 'Architecture'],
    colorClass: 'text-amber-300',
    progressColor: '#fcd34d',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400&h=120&fit=crop',
    projectCount: 94,
    aiProvider: 'Claude',
    aiModel: '3.5 Sonnet',
    aiLogoUrl: 'https://avatars.githubusercontent.com/u/76839336?s=200&v=4',
    currentTaskId: 'FS-66',
    currentTaskName: 'Building end-to-end user onboarding workflow'
  },
  {
    id: 'qa-lead',
    name: 'Olivia Martinez',
    title: 'QA Lead',
    emoji: '🦊',
    description: 'Quality strategy and test planning',
    icon: FlaskConical,
    status: 'idle',
    progress: 0,
    tags: ['Playwright', 'Reporting', 'Strategy'],
    colorClass: 'text-orange-400',
    progressColor: '#fb923c',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=400&h=120&fit=crop',
    projectCount: 28,
    aiProvider: 'Gemini',
    aiModel: '1.5 Pro',
    aiLogoUrl: 'https://www.gstatic.com/images/branding/product/2x/gemini_32dp.png',
    currentTaskId: 'QA-19',
    currentTaskName: 'Defining acceptance criteria for payment module'
  },
  {
    id: 'qa-auto-dev',
    name: 'Lucas White',
    title: 'QA Automation Dev',
    emoji: '🛠️',
    description: 'Automated test development',
    icon: Wrench,
    status: 'idle',
    progress: 0,
    tags: ['Jest', 'Unit Tests', 'Roadmap'],
    colorClass: 'text-slate-300',
    progressColor: '#cbd5e1',
    avatarUrl: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=150&h=150&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=400&h=120&fit=crop',
    projectCount: 47,
    aiProvider: 'ChatGPT',
    aiModel: 'GPT-4o',
    aiLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    currentTaskId: 'TEST-35',
    currentTaskName: 'Writing integration tests for API gateway'
  }
];
